/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * Copyright (c) 2021 Martin Jäger / Libre Solar
 */

#define CONFIG_THINGSET_EXPERT_PASSWORD "expert123"
#define CONFIG_THINGSET_MAKER_PASSWORD "maker456"

#define CONFIG_THINGSET_SERIAL 1
#define CONFIG_THINGSET_SERIAL_TX_BUF_SIZE 500
#define CONFIG_THINGSET_SERIAL_RX_BUF_SIZE 500

#define CONFIG_THINGSET_CAN 1
#define CONFIG_THINGSET_CAN_DEFAULT_NODE_ID 20
