/*
 * Copyright (c) The Libre Solar Project Contributors
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#define CONFIG_THINGSET_EXPERT_PASSWORD "expert123"
#define CONFIG_THINGSET_MAKER_PASSWORD "maker456"

#define CONFIG_THINGSET_SERIAL 1
#define CONFIG_THINGSET_SERIAL_TX_BUF_SIZE 500
#define CONFIG_THINGSET_SERIAL_RX_BUF_SIZE 500

#define CONFIG_THINGSET_CAN 1
#define CONFIG_THINGSET_CAN_DEFAULT_NODE_ID 20

#define CONFIG_BAT_CAPACITY_AH 45
#define CONFIG_CELL_TYPE_LFP 1
#define CONFIG_CELL_TYPE 1
#define CONFIG_NUM_CELLS_IN_SERIES 8
