# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: libresolar
      url-base: https://github.com/LibreSolar
    - name: thingset
      url-base: https://github.com/ThingSet
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
  projects:
    - name: zephyr
      remote: zephyrproject
      revision: v3.5-branch
      import:
        name-allowlist:
          - cmsis
          - edtt
          - hal_espressif
          - hal_stm32
          - tinycrypt
    - name: thingset-zephyr-sdk
      remote: thingset
      revision: 46c6e19af7ef7e5badc1ba5a900f6fde92e08fb2
      path: thingset-zephyr-sdk
      import:
        name-allowlist:
          - thingset-node-c
          - zcbor
