# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: libresolar
      url-base: https://github.com/LibreSolar
    - name: thingset
      url-base: https://github.com/ThingSet
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
  projects:
    - name: zephyr
      remote: zephyrproject
      revision: v4.0-branch
      import:
        name-allowlist:
          - cmsis
          - edtt
          - hal_espressif
          - hal_stm32
          - mcuboot
          - tinycrypt
          - zcbor
    - name: thingset-zephyr-sdk
      remote: thingset
      revision: 48740769cea0d9666fc9132cd8923f9ce2c088f9
      path: thingset-zephyr-sdk
      import:
        name-allowlist:
          - thingset-node-c
          - zcbor
