# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: libresolar
      url-base: https://github.com/LibreSolar
    - name: thingset
      url-base: https://github.com/ThingSet
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.1-branch
      import:
        name-whitelist:
          - cmsis
          - edtt
          - hal_espressif
          - hal_stm32
    - name: oled-display-library
      remote: libresolar
      revision: cc3033c0daace8cb50ab0e6406a9498cc81cdb39
      path: modules/oled-display
    - name: thingset-device-library
      remote: thingset
      revision: 5c2b562d77cd44969c822bbd8c37cd7394d5ca58
      path: modules/thingset
    - name: unity
      remote: throwtheswitch
      revision: 74cde089e65c3435ce9aa87d5c69f4f16b7f6ade
      path: modules/unity
