# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: libresolar
      url-base: https://github.com/LibreSolar
    - name: thingset
      url-base: https://github.com/ThingSet
    - name: throwtheswitch
      url-base: https://github.com/ThrowTheSwitch
  projects:
    - name: zephyr
      remote: zephyrproject
      revision: v4.3-branch
      import:
        name-allowlist:
          - cmsis_6
          - edtt
          - hal_espressif
          - hal_stm32
          - mbedtls
          - mcuboot
          - tinycrypt
          - zcbor
    - name: thingset-zephyr-sdk
      remote: thingset
      revision: b9d300777b669cf3830556cb1a7b41c59b0608e2
      path: thingset-zephyr-sdk
      import:
        name-allowlist:
          - thingset-node-c
          - zcbor
