name: Code check and build tests

on: [push, pull_request]

jobs:
  zephyr:
    # Avoid running twice if pushing to a PR branch in the base repo
    if: >
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firmware
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: firmware
          fetch-depth: 0 # necessary to get tags

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Zephyr project setup
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: firmware
          toolchains: arm-zephyr-eabi:riscv64-zephyr-elf

      - name: Coding style check
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-15 colordiff
          git status
          bash scripts/check-style.sh

      - name: Fetch hal_espressif binary blobs
        run: |
          west blobs fetch hal_espressif

      - name: Build firmware
        run: |
          west twister -T ./app --build-only --inline-logs -n

      - name: Run unit-tests
        run: |
          west twister -T ./tests --integration --inline-logs -n
